version = 1

exclude_patterns = [
    ".github/**",
    ".gitignore",
    "README.md",
    "package-lock.json",
    "package.json"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["nodejs"]
